### ISSUE TITLE
RegExp flags are removed

### ISSUE THREAD

**Issue by xblanc33** [fczbkk/css-selector-generator#183]
convertMatchListToRegExp() removes all flags as it uses the RegExp.source property (see utilities-data.ts line 47)

Not so easy to define what should be the correct behavior but I would advocate that the 'i' flag is very useful ;)
BTW the 'g' flag is not useful as css-selector-generator only tests the RegExp..

Why not setting a 'i' flag if at least one of the RegExp of the list defines it ?

I can make the PR if your want to.

Regards

**Comment by fczbkk** [comment]
Hey @xblanc33, thanks for the report. The RegExp patterns should be fixed now so that they will respect provided flags. Please update to `v3.5.4`.

**Comment by xblanc33** [comment]
Great using some is what I was thinking of.
Is it faster than creating one main big RegExp expression ?

**Comment by fczbkk** [comment]
> Is it faster than creating one main big RegExp expression ?

It is not possible to create a single RegExp that will use different flags for parts of the expression. So that's not even an option. Anyway, I don't think it really matters in this case, as the volume of checked items is quite small. So the performance in common situations should be practically the same (almost zero).
