### ISSUE TITLE
Allow custom filter functions as blacklist/whitelist 

### ISSUE THREAD

**Issue by fregante** [fczbkk/css-selector-generator#212]
The selector filters only accept regexes and strings:

https://github.com/fczbkk/css-selector-generator/blob/3c5b2c2ad536e246a9cf5798891d48e9db2b9424/src/utilities-options.ts#L19-L20
https://github.com/fczbkk/css-selector-generator/blob/3c5b2c2ad536e246a9cf5798891d48e9db2b9424/src/types.ts#L4

Would you accept a PR to add support for functions? Example:

```js
getCssSelector(
  targetElement,
  { blacklist:
      [
        // ID selector
        '#forbiddenId',

        // predicate function
        selector => !isCoolSelector(selector)
      ]
  }
)
```

**Comment by fczbkk** [comment]
Hey @fregante, thanks for the suggestion and for the pull request. In the end, I did not use your pull request, because I wanted to implement it in a slightly different way and I also wanted to add more tests and update documentation.

I have generated `v3.6.0`, which includes this feature. See:
https://www.npmjs.com/package/css-selector-generator/v/3.6.0#blacklist
