### ISSUE TITLE
Failed to load source map warning in production build

### ISSUE THREAD

**Issue by zicsus** [fczbkk/css-selector-generator#229]
I'm using this library in my chrome extension, and it looks like it uses source maps in the production build for some reason. 

Here is the warning- 
![cssselector](https://user-images.githubusercontent.com/31795543/157200775-838eca2f-28c0-4c71-9e4c-ad4d5645590e.PNG)

This looks like a recent issue as I didn't experience this before as far as I remember, but I might be wrong.

**Comment by fczbkk** [comment]
Hey @zicsus. Please provide me with more info. How are you using this library in your extension? Do you use some build system, or do you just copy files into it?

**Comment by zicsus** [comment]
Hi @fczbkk, Thanks for responding!

I use gulp and Webpack and using simple `import getCssSelector from 'css-selector-generator';` 

I'm using version 3.6.0

**Comment by fczbkk** [comment]
@zicsus I have created a repo with the most basic Webpack config:
https://github.com/fczbkk/css-selector-generator-with-webpack

It looks like it is working fine. After I build the source code (`npm run build`), the generated file (see `/build` directory) does not produce any errors or warnings.

Can you please share your Webpack config, so that I can reproduce your problem? Or you can do a pull request to the repo.

**Comment by zicsus** [comment]
Hi, 

I use Extension CLI for my extension- https://github.com/zicsus/extension-cli
Here is the file that is used for building the extension- https://github.com/zicsus/extension-cli/blob/master/config/gulpfile.js

Thanks!

**Comment by fczbkk** [comment]
@zicsus Ok, so that's the tool you use. But I have no idea how your project looks like and thus no way to replicate your issue.

My guess is that this tool just copies the JS files of CssSelectorGenerator library and skips the source map files. But that's just a guess. I can't do more until I have a way to replicate the issue.

**Comment by zicsus** [comment]
Hey @fczbkk, I found out the issue!
Some problem with my config.

Sorry for the inconvenience! :(

**Comment by fczbkk** [comment]
@zicsus I'm glad to hear you've been able to resolve this. Would you mind sharing what was wrong, in case someone else has similar problem in the future?
