### ISSUE TITLE
Does element selectors like `>, +, ~ ` are working? 

### ISSUE THREAD

**Issue by jcforest** [fczbkk/css-selector-generator#350]
I want to query selectors with `>, +, ~` selectors because sometimes it provides shorter selector.
How can I pass above selectors to selectors list?

**Comment by fczbkk** [comment]
Hey @jcforest, thanks for the question.

The library uses the [child combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator) `>` for fallback selectors, as it is the only way to ensure unique selector for otherwise unidentifiable elements. It will also use it when generating candidate selectors, but to be honest, these are rarely used, because there are usually better candidates. You would have to severely limit considered selector types (e.g. only allow "tag" selectors) to see child combinators surface.

The sibling combinator selectors (`+` and `~`) are not used by this library. The algorithm that I use traverses through parents of target elements and I would have to rewrite the logic completely for it to account for sibling elements. Also, such change would rise the complexity and number of operations drastically. So I currently have no plans to implement them.

If you have specific scenario, where these selectors would provide significantly better results, please reopen this issue and let me know in the comment. Maybe I could figure out some solution.
