### ISSUE TITLE
Feature request : multiple elements as parameters

### ISSUE THREAD

**Issue by lilacdev** [fczbkk/css-selector-generator#58]
Hi again,

Do you think this could be possible to generate a selector from multiple elements ?

For example :
```html
<body>
  <article class="article1"></article>
  <article class="article2"></article>
</body>
```
When we pass element article1 element, this generates `.article1`. (working as this today).

And then, if we pass an array of elements (let's say article1 and article2), this would generate `article`

**Comment by fczbkk** [comment]
**Short answer:**

No.

**Long answer:**

Yes.

But it would be very complicated and there would be a lot of problems. First problem is, that with single elements, you can always generate a selector (fallback selectors can be ugly `nth-child` child chains, but they work), but there are lots of situations when it's just not possible to create a common selector for multiple elements. Well, maybe with some excessive use of wildcards and negations... But that would be a selector hell.

Second problem is exponential complexity. In your example, it would be easy to create all selectors for all elements, test them all and find the ones that match both target elements. But with each added node to the DOM, that complexity grows exponentially. Try looking at the DOM structure of any Facebook page. See all the DIVs with random class names? I don't think there are enough atoms in the universe to count all the combinations of possible CSS selectors for each of them.

I try to do some smart things to lower this complexity. I'm trying to generate partial selectors with higher specificity for parents of the target element, so that I can throw away whole branches of selectors without potential before I have to go through all of them. But even that often requires generating lots of selector candidates and testing if they work. I just can't think of a simple algorithm that will do that for multiple elements at once.

So... no.

**Comment by lilacdev** [comment]
Thanks for this clarification.

**Comment by lilacdev** [comment]
Hi,
I noticed you finally did it, did you ? :)
```
getCssSelector([firstElement, secondElement])
```

**Comment by fczbkk** [comment]
@lilacdev Yeah, I came up with a way to implement it. It's not perfect and there are several edge cases where it will not work. But it seems to be working fine most of the time. The only thing is, that when it is not possible to find a common selector, it will have to generate standalone selector for each element and just join them.

So, if we will modify your example like this:

```html
<body>
  <div class="article1"></div>
  <span class="article2"></span>
</body>
```

Then the resulting selector will be:

```
.article1, .article2
```

**Comment by lilacdev** [comment]
Awesome ! I will test it asap. Thank you. Issue #65 is quite blocking ATM, but if it can help, it was already there before your recent updates.

Thanks again and have a nice day !
