### ISSUE TITLE
Doesn't work as a CommonJS module

### ISSUE THREAD

**Issue by jribbens** [fczbkk/css-selector-generator#59]
```
$ node
Welcome to Node.js v15.14.0.
Type ".help" for more information.
> require('css-selector-generator')
Uncaught ReferenceError: self is not defined
```

**Comment by fczbkk** [comment]
This library is intended for browser use. There's no reason to use it in Node, because there are no elements.

If you are trying to use this library with some virtual DOM library, you'll have to add it to the virtual `window` object instead of directly requiring it into the Node process. Here's an example for JSDOM:

https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global
