### ISSUE TITLE
Not working as expected with custom HTML elements

### ISSUE THREAD

**Issue by djob** [fczbkk/css-selector-generator#61]
Just tried library on youtube.com and it seems that it doesn't work with custom HTML elements at all.
When trying to get selector for action menu button I got following:
```
:root > :nth-child(2) > :nth-child(4) > :nth-child(12) > :nth-child(4) > :nth-child(1) > :nth-child(8) > :nth-child(1) > :nth-child(1) > :nth-child(6) > :nth-child(5) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(2) > :nth-child(3) > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(1)
```
but it should be something like:
```
ytd-page-manager > ytd-browse > ytd-two-column-browse-results > #primary > #contents > ytd-rich-item-renderer > #content > ytd-rich-grid-media > #details > ytd-menu-renderer > ytd-icon-button > button
```
according to:
![image](https://user-images.githubusercontent.com/818443/118561893-08fbc200-b76c-11eb-8fac-7f5893a318e3.png)

I tried passing several combination of options to  getCssSelector function but didn't help much.

Am I missing something?

**Comment by fczbkk** [comment]
@djob The selector using `:nth-child()` selectors is fallback selector. This is used when the generator is not able to produce unique selector using other types of selectors. Custom tag names should not be a problem, the library can handle them, even the namespaced ones:
https://github.com/fczbkk/css-selector-generator/blob/master/test/selector-tag.spec.js#L24-L30

**Comment by djob** [comment]
@fczbkk so basically library is not able to find unique selector from given example?

**Comment by fczbkk** [comment]
@djob The first selector you posted (the  `nth-child` one) is the unique selector. The library is not able to create a unique selector of given element using tag selectors, because that's probably impossible in this situation.

Imagine this situation:

```html
<div>first</div>
<div>second</div>
```

There is no way to create a unique CSS selector of first DIV using tag selectors. You can only target it using something like this:

```
:root > :nth-child(1)
```

The selector you posted is probably something like that, just with deeper nesting.
