### ISSUE TITLE
Generate non-unique selectors

### ISSUE THREAD

**Issue by Andrii-Vovk** [fczbkk/css-selector-generator#688]
By default, the library tries to create a selector, that will only select those particular elements, and no other ones.

For my use case, I need to select a few elements in the list, and then create a selector, that will select all the elements in that list.

Example:
Here, all elements in the list are selected; Correct selector is generated.
<img width="1426" alt="image" src="https://github.com/user-attachments/assets/94631595-78af-4a73-babc-0b2c57a78a14">
Here, only 2 out of 3 elements are selected, lib falls back to id's, to select only the two elements.
<img width="1441" alt="image" src="https://github.com/user-attachments/assets/6f4f7cc3-25b6-4b05-94f9-cf88d09407b5">
 

Is there a way to change that behaviour? Or am I approaching the problem from the wrong angle?

Any help will be greatly appreciated. Thanks in advance!

**Comment by fczbkk** [comment]
Hey @Andrii-Vovk, if I understand correctly, you are looking for something that:

- you will provide a sample of elements,
- it will look for commonalities between them,
- apply some fuzzy logic to find all elements that share these commonalities
- and then try to generate a CSS selector that will target all those elements.

The focus of this library is to generate unique CSS selectors for the provided elements. So it can't do that for you.

Unfortunately, I don't know about any library that looks for elements based on commonalities with a provided sample. If you find some, please let me know, because I'm sure it would be a great complement to CSS Selector Generator.
